apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: helloworld-pod
  name: helloworld-pod
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld-pod
  sessionAffinity: None
  type: LoadBalancer
