steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/sample-sb:$TAG_NAME', '.']
images: ['gcr.io/$PROJECT_ID/sample-sb:$TAG_NAME']
